project_id = "wwkscenkrhqcjuptsshh"

[functions.chat]
verify_jwt = false

[functions.generate-question]
verify_jwt = false


[functions.seed-questions]
verify_jwt = false

[functions.get-games]
verify_jwt = false

[functions.get-user-stats]
verify_jwt = false

[functions.submit-result]
verify_jwt = false

[functions.update-game-progress]
verify_jwt = false

[functions.award-badge]
verify_jwt = false